name: dotnet package

on: [push]

jobs:
    build:
        
        runs-on: windows-latest
        strategy:
            matrix:
                dotnet-version: [ '4.8.1' ]
        
        steps:
          - uses: actions/checkout@v3

          - name: Setup MSBuild
            uses: microsoft/setup-msbuild@v1.1.3

          - name: Setup NuGet
            uses: NuGet/setup-nuget@v1.1.1
            
          - name: Nuget restore
            run: nuget restore PDFCreatorFromImages.sln
            
          - name: Build
            run: msbuild PDFCreatorFromImages.sln
            
